// let nombre = prompt ("Ingresa tu nombre.")
// let apellido = prompt ("Ingresa tu apellido.")
// let ciudad = prompt ("Ingresa donde naciste.")
// let dia = prompt ("Ingresa tu dia de nacimiento.")
// let mes = prompt ("Ingresa tu mes de nacimiento (escrito).")
// let año = prompt ("Ingresa tu año de nacimiento.")
// let destino = prompt ("Ingresa el destino que prefieras, playa, montaña, etc.")
// let lugar = prompt ("Ingresa el lugar soñado para ir.")

// alert("Mi nombre y apellido es " + nombre + " " + apellido + ", soy de " + ciudad + ", naci el " + dia + " de " + mes + " de " + año + ". Me gusta ir de vacaciones a la " + destino + ", el lugar soñado es " + lugar + ".")

// console.log(nombre)
// console.log(apellido)
// console.log(ciudad)
// console.log(dia)
// console.log(mes)
// console.log(año)
// console.log(destino)
// console.log(lugar) 